### ISSUE TITLE
Use of uninitialized value $len in division (/) at mapAndGc.pl line 83

### ISSUE THREAD

**Issue by Giuseppe1995** [chrisamiller/copyCat#18]
Hi, 
I wanted to perform a copy number analysis on WGS samples according to [this tutorial](https://pmbio.org/module-05-somatic/0005/04/01/Somatic_CNV_Calling/), but, when creating the annotation directory (the one with mappability and gc content files) I get this error: 

> Use of uninitialized value $len in division (/) at mapAndGc.pl line 83

Now, I've tried several things before submitting this issue, but anything seems to work. I've also run each command of the script `runEachChr.sh` on my own, and the problem seems to be this command:
`perl mapAndGc.pl $outdir/copyCat_annotation/$fasta_name.sam $entrypoint $windowSize $fasta_name $readLength $outdir/copyCat_annotation`.

Here come the arguments I passed to the `runEachChr.sh` script:

single_record_fasta: GRCh37.fa, downoaded [here](https://ewels.github.io/AWS-iGenomes/)
multi_record_fasta: Y.fa, which is basically the fasta file of chrY of GRCh37
readLength: 150 
entrypoint*: GRCh37entrypoints.male
outdir: annodir

*Here is the `cat` of this file (it's tab-separated):

> 1	249250621	2
> 2	243199373	2
> 3	198022430	2
> 4	191154276	2
> 5	180915260	2
> 6	171115067	2
> 7	159138663	2
> 8	146364022	2
> 9	141213431	2
> 10	135534747	2
> 11	135006516	2
> 12	133851895	2
> 13	115169878	2
> 14	107349540	2
> 15	102531392	2
> 16	90354753	2
> 17	81195210	2
> 18	78077248	2
> 19	59128983	2
> 20	63025520	2
> 21	48129895	2
> 22	51304566	2
> X	155270560	1
> Y	59373566	1

I am pretty sure that the problem stands in the file  GRCh37entrypoints.male, but in facts I've never programmed in perl, so I don't have a clue of how to solve this problem.

Thank you in advance for your help,
Guseppe

**Comment by chrisamiller** [comment]
I don't have the bandwidth to provide support for copyCat at the moment, but I can tell you that at the end of the day, that script just creates all possible reads of a given size from the genome, maps them back using bwa mem (or sub in your aligner of choice), then counts the number of reads that mapped correctly and unambiguously back to each window across the genome.  It would be fairly straightforward to rewrite in just about any programming language if that's your goal.

As an FYI, I'm not really developing this software anymore - there's nothing fundamentally wrong with it, but tools like CNVkit are more polished at this point. Best of luck!
