### ISSUE TITLE
Limit memory usage of copyCat

### ISSUE THREAD

**Issue by weijianwen** [chrisamiller/copyCat#2]
Hi,

Some of copyCat jobs failed on our 256GB servers due to memory overload. Is it possible to limit memory usage of copyCat?

Best,

**Comment by chrisamiller** [comment]
Can you provide more information about what step is using that much memory? What params are you running it with? What's your window size?

**Comment by weijianwen** [comment]
Sure. Here is the R script we use. The size of the *.windfile is ~56MB.

```
library(copyCat)
#The most convenient way to run copyCat is through the functions in meta.R.
#For a paired tumor/normal sample, this looks something like this:
runPairedSampleAnalysis(annotationDirectory="/lustre/home/medzm/annotation/copyCat_ann/hg19/copycat.anno.hg19",
                        outputDirectory="FHM-RL_CNV_out",
                        normal="WGC037211D_mem.grp.1000.windfile",
                        tumor="WGC037811D_mem.grp.1000.windfile",
                        inputType="bins",
                        maxCores=8,
                        binSize=0, #infer automatically from bam-window output
                        perLibrary=1, #correct each library independently
                        perReadLength=1, #correct each read-length independently
                        verbose=TRUE,
                        minWidth=3, #minimum number of consecutive winds need to call CN
                        minMapability=0.6, #a good default
                        dumpBins=TRUE,
                        doGcCorrection=TRUE,
                        samtoolsFileFormat="10colPileup", #will infer automatically - mpileup 10col or VCF
                        purity=1,
                        normalSamtoolsFile="WGC037211D_mem.grp.10col.mpileup",
                        tumorSamtoolsFile="WGC037811D_mem.grp.10col.mpileup")
```

**Comment by chrisamiller** [comment]
- What size are the windows within that wind file (10,000 bp? 1000 bp?)  
- How large are the mpileup files?  
- What depth is your sequencing?

**Comment by weijianwen** [comment]
The window size is 1000bp, the mpileup files are 241GB for each and the average depth of wgs is 30x.

Thank you.

**Comment by chrisamiller** [comment]
Woah - Those 241GB mpileup files are your problem!  On 30x WGS, I'd expect
more like 5 million lines and 1GB, max. Check your params and data for
sanity.

**Comment by weijianwen** [comment]
Thank you, Chisa. Any suggestion for runnning such a big case on a 256GB machine? Or should I just  buy a bigger machine to hold it :-)

**Comment by chrisamiller** [comment]
I think you need to question the data and parameters that were given to
mpileup that result in a 241GB file. Something is probably wrong when
you've produced a pileup that's massively larger than your bam file.

**Comment by zhaoming159753** [comment]
My bam file is about 40G and I use : samtools mpileup -f ref.fa my.bam > my.mpileup, the result my.mpileup is 240G.
Could you give some guide to generate the mpileup file form a bam?

**Comment by chrisamiller** [comment]
Look at your mpileup file to see if anything looks amiss. For example, do the chromosomes in your fasta match your bam? (chr1 vs 1)? If not, then every base will be called as a variant, and that could result in enormous mpileup output like you're seeing.
