### ISSUE TITLE
error msg 

### ISSUE THREAD

**Issue by sunyounglee** [chrisamiller/copyCat#7]
Hi, I'm trying to run the copycat.
Following the code in manual (https://github.com/chrisamiller/copycat/, Usage), I have some problems when I running it.

I got the error msg below:

[1] "inferred bin size:  1000"
[1] "calculating mapability content for read length 101 Sat Nov 19 15:48:54 2016"
[1] "WARNING: annotations for read length of 101 don't exist"
[1] "using annotations for read length of 100 which are close enough"
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 0, 2

My input files are:
1) bam window files for normal and tumor data generated from bam-window with -r (by read length) and -l (by library) options
Chr     Start   GI10_N.101
chrM    1       222
chrM    1001    141
chrM    2001    144
chrM    3001    179
.
.
.

2) vcf files generated from samtools mpileup command

Here is the code I run:

runPairedSampleAnalysis(annotationDirectory="/Volumes/sylee1/SunYoung/Project/Clonality_Analysis/annotations/copycat.anno.hg19", outputDirectory="ccout", normal="/Volumes/sylee1/SunYoung/Project/Clonality_Analysis/GI10N_window", tumor="/Volumes/sylee1/SunYoung/Project/Clonality_Analysis/GI10T_window", inputType = "bins", maxCore=2, binSize=0, perLibrary=1, perReadLength=1, verbose=TRUE, minWidth=3, minMapability=0.6, dumpBins=TRUE, doGcCorrection=TRUE, samtoolsFileFormat="unknown", purity=1, normalSamtoolsFile="/Volumes/sylee1/SunYoung/Project/Clonality_Analysis/GI10N.raw.vcf", tumorSamtoolsFile="/Volumes/sylee1/SunYoung/Project/Clonality_Analysis/GI10T.raw.vcf”)

Do I something wrong? 
Could you let me know how I can run the copyCat?

**Comment by thestarocean** [comment]
I encounter the same problem while I used mpileup for samtoolsFile. Did you solve the problem?

**Comment by thestarocean** [comment]
I think I found the problem. This could be caused by differences between the chromosome names used in bam-window-files (eg. chr1, chr2……) and those used in annotation (with 1,2,3……) .
