### ISSUE TITLE
detail methods in copycat

### ISSUE THREAD

**Issue by Xiaohuaniu0032** [chrisamiller/copyCat#9]
hi, does copyCat have a peer-reviewed paper?i want to look the detail methods of it. thanks a lot.

**Comment by chrisamiller** [comment]
Nope - I've never gotten around to publishing it, though it's been used in many studies.  The methods are conceptually similar to those in the readDepth paper, published here: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0016327
